name: Test and Coverage
on: [push, pull_request]
#on:
#  push:
#    branches:
#      - main
#    pull_request:
#      branches:
#        - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Download & Run gotestsum
        run: |
          go get gotest.tools/gotestsum
          GOFLAGS=-mod=mod gotestsum --jsonfile report.json -- -race -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./report.json,./coverage.out # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
#      - name: Upload Test Coverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)