name: Test and Coverage
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Download & Run gotestsum
        run: |
          go get gotest.tools/gotestsum
          GOFLAGS=-mod=mod gotestsum --jsonfile report.json -- -race -coverprofile=coverage.out ./...
      - name: Upload Test Coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)